# Site settings
site: kakarotwrites.github.io
title: Rifat Al Jubayer 
keywords: rifat blog
description: >-
  Portfolio and blog showcasing projects and academic achievements.
lang: en-US
timezone: Asia/Jakarta
repo: https://github.com/kakarotsec # site repo [optional]
# google_verify:      XXX # Put your Google Verification here
# google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
# google_verify:      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# google_analytics:   UA-XXXXXXXX-00
discus-identifier:  ariafatah0711

# Author settings
author:
  name: Rifat Al Jubayer
  bio: Cybersecurity Researcher <br> Web Security & Development <br> Network Security & Exploits <br> DevSecOps & Automation
  # bio: Hoby Belajar IT web development ppppppppppppppppppppp ddddddddddddddddddddd  12312 4234 342423 42422 dancokkkk kk kk kk
  picture: assets/images/pic3.jpg
  github: kakarotsec # github username
  # twitter:  # twitter username
  # facebook:  # facebook username
  instagram: kakarot.ping # instagram username
  # youtube: https://www.youtube.com/channel/# youtube username
  linkedin: rifat-al-jubayer
  email: rifataljubaer2@gmail.com
  discord: https://discord.gg/J3tH4rNT

app:
  theme: dark
  navbar:
    - name: about
      url: /about
    - name: cv
      url: /cv
    # - name: notes
    #   url: /notes
    # - name: blogs
    #   url: /blogs
    # - name: urls
    #   url: /urls
    - name: tags
      url: /tags
    # - name: repos
      # url: repos
    - name: info
      url: /info
    # - name: /external
    #   url: https://docs.ariaf.my.id
  linktree:
    active: true
    groups:
      - title: Linktree
        items:
          - name: WhatsApp
            url: https://wa.me/qr/IFWCFCOO2P5HA1
          # - name: GitHub
          #   url: https://github.com/ariafatah0711
      - title: My Web
        items:
          - name: notes
            url: https://ariaf.my.id/notes
          - name: files
            url: https://ariaf.my.id/files
          - name: ctf
            url: https://ctf.ariaf.my.id
  show_discord:
    active: True
    discord_id: 879547455941779456
    cacheTime: 15000
  toggle_song:
    active: False
    song: assets/song/song.m4a

# pwa (opsional)
# pwa:
#   enabled: true
#   sw_src_filepath: service-worker.js # Optional
#   sw_dest_filename: service-worker.js # Optional
#   dest_js_directory: assets/js # Required
#   precache_recent_posts_num: 5 # Optional
#   precache_glob_directory: / # Optional
#   precache_glob_patterns:
#     - "{js,css,fonts,img}/**/*.{js,css,eot,svg,ttf,woff,png,avif,jpg,jpeg,gif,webp}"
#     - index.html
#   precache_glob_ignores: # Optional
#     - sw-register.js
#     - "fonts/**/*"

# URL settings
url: "https://kakarotwrites.github.io"
# url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  # - jekyll-pwa-plugin

paginate: 10
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
